/*
 * Заказ ресурсов на облаке
 * Тестовый API для домашнего задания GB
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Cloud;
import io.swagger.client.model.Clouds;
import io.swagger.client.model.Error;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for OrdersApi
 */
@Ignore
public class OrdersApiTest {

    private final OrdersApi api = new OrdersApi();

    /**
     * Метод отмены заказа на облако по ID
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void canceledByIdTest() throws Exception {
        String cloudId = null;
        api.canceledById(cloudId);

        // TODO: test validations
    }
    /**
     * Создание заказа на облако
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createCloudTest() throws Exception {
        Error body = null;
        Clouds response = api.createCloud(body);

        // TODO: test validations
    }
    /**
     * Метод получения заказа на облако по ID
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCloudByIdTest() throws Exception {
        String cloudId = null;
        Cloud response = api.getCloudById(cloudId);

        // TODO: test validations
    }
}
