/*
 * Заказ ресурсов на облаке
 * Тестовый API для домашнего задания GB
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * OS
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-08-08T16:28:18.063728446Z[GMT]")

public class OS {
  @SerializedName("os_id")
  private String osId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("os_group")
  private String osGroup = null;

  @SerializedName("os_version")
  private String osVersion = null;

  @SerializedName("language")
  private String language = null;

  @SerializedName("price")
  private String price = null;

  public OS osId(String osId) {
    this.osId = osId;
    return this;
  }

   /**
   * ID операционки
   * @return osId
  **/
  @Schema(example = "f102b615", required = true, description = "ID операционки")
  public String getOsId() {
    return osId;
  }

  public void setOsId(String osId) {
    this.osId = osId;
  }

  public OS name(String name) {
    this.name = name;
    return this;
  }

   /**
   * название операционки
   * @return name
  **/
  @Schema(example = "Linux", required = true, description = "название операционки")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public OS osGroup(String osGroup) {
    this.osGroup = osGroup;
    return this;
  }

   /**
   * название семейства ОS
   * @return osGroup
  **/
  @Schema(example = "Ubuntu", required = true, description = "название семейства ОS")
  public String getOsGroup() {
    return osGroup;
  }

  public void setOsGroup(String osGroup) {
    this.osGroup = osGroup;
  }

  public OS osVersion(String osVersion) {
    this.osVersion = osVersion;
    return this;
  }

   /**
   * версия ОS
   * @return osVersion
  **/
  @Schema(example = "10.5", required = true, description = "версия ОS")
  public String getOsVersion() {
    return osVersion;
  }

  public void setOsVersion(String osVersion) {
    this.osVersion = osVersion;
  }

  public OS language(String language) {
    this.language = language;
    return this;
  }

   /**
   * язык ОS
   * @return language
  **/
  @Schema(example = "rus", required = true, description = "язык ОS")
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public OS price(String price) {
    this.price = price;
    return this;
  }

   /**
   * цена использования ОS
   * @return price
  **/
  @Schema(example = "200.5", required = true, description = "цена использования ОS")
  public String getPrice() {
    return price;
  }

  public void setPrice(String price) {
    this.price = price;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OS OS = (OS) o;
    return Objects.equals(this.osId, OS.osId) &&
        Objects.equals(this.name, OS.name) &&
        Objects.equals(this.osGroup, OS.osGroup) &&
        Objects.equals(this.osVersion, OS.osVersion) &&
        Objects.equals(this.language, OS.language) &&
        Objects.equals(this.price, OS.price);
  }

  @Override
  public int hashCode() {
    return Objects.hash(osId, name, osGroup, osVersion, language, price);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OS {\n");
    
    sb.append("    osId: ").append(toIndentedString(osId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    osGroup: ").append(toIndentedString(osGroup)).append("\n");
    sb.append("    osVersion: ").append(toIndentedString(osVersion)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
